name: Debug

on:
  push:
    branches: [feature/dotnet10]

jobs:

  debug:
    name: Debug
    runs-on: windows-2025-vs2026
    steps:
      - name: Print Some Stuff
        shell: pwsh
        run: |
          ls "C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\"
